version: "3.4"

x-base: &base
  build:
    args:
      - HTTP_PROXY
      - HTTPS_PROXY
      - VERSION=0.0.0.0
  environment:
    - HTTP_PROXY
    - HTTPS_PROXY
    - LABATT_CONFIGURATION
  volumes:
    - labatt:/labatt

services:
  template-web:
    <<: *base
    ports:
      - 8000:8000
  tests: *base

volumes:
  labatt:
    external: yes
