version: "3.4"

x-base-build: &base-build
  context: .
  args:
    - DOCKER_REGISTRY
    - DOTNET_RESTORE_VERBOSITY=${DOTNET_RESTORE_VERBOSITY:-minimal}
    - VERSION

services:
  template-web:
    build: *base-build
  api-tests:
    build:
      <<: *base-build
      target: api
    command: dotnet test --no-restore --no-build
    volumes:
      - type: bind
        source: ./project-template-api/TestResults
        target: /src/TestResults
  ui-tests:
    build:
      <<: *base-build
      target: ui
    command: npm run test:unit
