version: "3.4"

x-base-build: &base-build
  context: .
  args:
    - DOCKER_REGISTRY
    - VERSION

services:
  template-web:
    build: *base-build
  tests:
    build:
      <<: *base-build
      target: api
    command: dotnet test --no-restore --no-build
    volumes:
      - type: bind
        source: ./api/TestResults
        target: /src/TestResults
